package Modelo;
// Generated 17-abr-2018 11:54:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name="administrador"
    ,catalog="bbdd_g1"
)
public class Administrador  implements java.io.Serializable {


     private Integer idadministrador;
     private Set usuarios = new HashSet(0);

    public Administrador() {
    }

    public Administrador(Set usuarios) {
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDAdministrador", unique=true, nullable=false)
    public Integer getIdadministrador() {
        return this.idadministrador;
    }
    
    public void setIdadministrador(Integer idadministrador) {
        this.idadministrador = idadministrador;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="administradors")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


