package Modelo;
// Generated 17-abr-2018 11:54:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Maraton generated by hbm2java
 */
@Entity
@Table(name="maraton"
    ,catalog="bbdd_g1"
)
public class Maraton  implements java.io.Serializable {


     private Integer idmaraton;
     private Date fecha;
     private Double longitud;
     private String ubicacion;
     private Integer idjuez;
     private Set usuariomaratons = new HashSet(0);

    public Maraton() {
    }

    public Maraton(Date fecha, Double longitud, String ubicacion, Integer idjuez) {
       this.fecha = fecha;
       this.longitud = longitud;
       this.ubicacion = ubicacion;
       this.idjuez = idjuez;
    }
    
    public Maraton(Date fecha, Double longitud, String ubicacion, Integer idjuez, Set usuariomaratons) {
       this.fecha = fecha;
       this.longitud = longitud;
       this.ubicacion = ubicacion;
       this.idjuez = idjuez;
       this.usuariomaratons = usuariomaratons;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDMaraton", unique=true, nullable=false)
    public Integer getIdmaraton() {
        return this.idmaraton;
    }
    
    public void setIdmaraton(Integer idmaraton) {
        this.idmaraton = idmaraton;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="Longitud", precision=22, scale=0)
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="Ubicacion", length=45)
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    
    @Column(name="IDJuez")
    public Integer getIdjuez() {
        return this.idjuez;
    }
    
    public void setIdjuez(Integer idjuez) {
        this.idjuez = idjuez;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maraton")
    public Set getUsuariomaratons() {
        return this.usuariomaratons;
    }
    
    public void setUsuariomaratons(Set usuariomaratons) {
        this.usuariomaratons = usuariomaratons;
    }




}


