package Modelo;
// Generated 17-abr-2018 11:54:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Juez generated by hbm2java
 */
@Entity
@Table(name="juez"
    ,catalog="bbdd_g1"
)
public class Juez  implements java.io.Serializable {


     private Integer idjuez;
     private String disponibilidad;
     private Set usuarios = new HashSet(0);

    public Juez() {
    }

    public Juez(String disponibilidad, Set usuarios) {
       this.disponibilidad = disponibilidad;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDJuez", unique=true, nullable=false)
    public Integer getIdjuez() {
        return this.idjuez;
    }
    
    public void setIdjuez(Integer idjuez) {
        this.idjuez = idjuez;
    }

    
    @Column(name="Disponibilidad", length=45)
    public String getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(String disponibilidad) {
        this.disponibilidad = disponibilidad;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="usuariojuez", catalog="bbdd_g1", joinColumns = { 
        @JoinColumn(name="IDJuez", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="IDUsuario", nullable=false, updatable=false) })
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


