package Modelo;
// Generated 20-abr-2018 9:53:12 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Juezmaraton generated by hbm2java
 */
@Entity
@Table(name="juezmaraton"
    ,catalog="bbdd_g1"
)
public class Juezmaraton  implements java.io.Serializable {


     private JuezmaratonId id;
     private Date version;
     private Maraton maraton;
     private Usuario usuario;

    public Juezmaraton() {
    }

    public Juezmaraton(JuezmaratonId id, Maraton maraton, Usuario usuario) {
       this.id = id;
       this.maraton = maraton;
       this.usuario = usuario;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idmaraton", column=@Column(name="idmaraton", nullable=false) ), 
        @AttributeOverride(name="idusuario", column=@Column(name="idusuario", nullable=false) ) } )
    public JuezmaratonId getId() {
        return this.id;
    }
    
    public void setId(JuezmaratonId id) {
        this.id = id;
    }

    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="version", nullable=false, length=19)
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmaraton", nullable=false, insertable=false, updatable=false)
    public Maraton getMaraton() {
        return this.maraton;
    }
    
    public void setMaraton(Maraton maraton) {
        this.maraton = maraton;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idusuario", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


