package Modelo;
// Generated 20-abr-2018 9:53:12 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Maraton generated by hbm2java
 */
@Entity
@Table(name="maraton"
    ,catalog="bbdd_g1"
)
public class Maraton  implements java.io.Serializable {


     private Integer idmaraton;
     private Date version;
     private String nombre;
     private String longitud;
     private String ubicacion;
     private String fecha;
     private Set juezmaratons = new HashSet(0);
     private Set usuariomaratons = new HashSet(0);

    public Maraton() {
    }

    public Maraton(String nombre, String longitud, String ubicacion, String fecha, Set juezmaratons, Set usuariomaratons) {
       this.nombre = nombre;
       this.longitud = longitud;
       this.ubicacion = ubicacion;
       this.fecha = fecha;
       this.juezmaratons = juezmaratons;
       this.usuariomaratons = usuariomaratons;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmaraton", unique=true, nullable=false)
    public Integer getIdmaraton() {
        return this.idmaraton;
    }
    
    public void setIdmaraton(Integer idmaraton) {
        this.idmaraton = idmaraton;
    }

    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="version", nullable=false, length=19)
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="longitud", length=45)
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="ubicacion", length=45)
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    
    @Column(name="fecha", length=45)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maraton")
    public Set getJuezmaratons() {
        return this.juezmaratons;
    }
    
    public void setJuezmaratons(Set juezmaratons) {
        this.juezmaratons = juezmaratons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maraton")
    public Set getUsuariomaratons() {
        return this.usuariomaratons;
    }
    
    public void setUsuariomaratons(Set usuariomaratons) {
        this.usuariomaratons = usuariomaratons;
    }




}


