package Modelo;
// Generated 20-abr-2018 9:53:12 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="bbdd_g1"
)
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private Date version;
     private String nickname;
     private String password;
     private String email;
     private String telefono;
     private String dni;
     private Byte admin;
     private Byte juez;
     private Set juezmaratons = new HashSet(0);
     private Set usuariomaratons = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nickname, String password, String email, String telefono, String dni, Byte juez) {
       this.nickname = nickname;
       this.password = password;
       this.email = email;
       this.telefono = telefono;
       this.dni = dni;
       this.juez = juez;
    }
    
    public Usuario(String nickname, String password, String email, String telefono, String dni, Byte admin, Byte juez) {
       this.nickname = nickname;
       this.password = password;
       this.email = email;
       this.telefono = telefono;
       this.dni = dni;
       this.admin = admin;
       this.juez = juez;
    }
    
    public Usuario(String nickname, String password, String email, String telefono, String dni, Byte admin, Byte juez, Set juezmaratons, Set usuariomaratons) {
       this.nickname = nickname;
       this.password = password;
       this.email = email;
       this.telefono = telefono;
       this.dni = dni;
       this.admin = admin;
       this.juez = juez;
       this.juezmaratons = juezmaratons;
       this.usuariomaratons = usuariomaratons;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idusuario", unique=true, nullable=false)
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }

    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="version", nullable=false, length=19)
    public Date getVersion() {
        return this.version;
    }
    
    public void setVersion(Date version) {
        this.version = version;
    }

    
    @Column(name="nickname", length=45)
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    
    @Column(name="password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="dni", length=45)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="admin")
    public Byte getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Byte admin) {
        this.admin = admin;
    }

    
    @Column(name="juez")
    public Byte getJuez() {
        return this.juez;
    }
    
    public void setJuez(Byte juez) {
        this.juez = juez;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getJuezmaratons() {
        return this.juezmaratons;
    }
    
    public void setJuezmaratons(Set juezmaratons) {
        this.juezmaratons = juezmaratons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getUsuariomaratons() {
        return this.usuariomaratons;
    }
    
    public void setUsuariomaratons(Set usuariomaratons) {
        this.usuariomaratons = usuariomaratons;
    }




}


