package Modelo;
// Generated 20-abr-2018 9:53:12 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuariomaratonId generated by hbm2java
 */
@Embeddable
public class UsuariomaratonId  implements java.io.Serializable {


     private int idmaraton;
     private int idusuario;

    public UsuariomaratonId() {
    }

    public UsuariomaratonId(int idmaraton, int idusuario) {
       this.idmaraton = idmaraton;
       this.idusuario = idusuario;
    }
   


    @Column(name="idmaraton", nullable=false)
    public int getIdmaraton() {
        return this.idmaraton;
    }
    
    public void setIdmaraton(int idmaraton) {
        this.idmaraton = idmaraton;
    }


    @Column(name="idusuario", nullable=false)
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuariomaratonId) ) return false;
		 UsuariomaratonId castOther = ( UsuariomaratonId ) other; 
         
		 return (this.getIdmaraton()==castOther.getIdmaraton())
 && (this.getIdusuario()==castOther.getIdusuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdmaraton();
         result = 37 * result + this.getIdusuario();
         return result;
   }   


}


